### ISSUE TITLE
don´t get any values / now wrong values

### ISSUE THREAD

**Issue by PapaSchIumpf** [NorthernWidget-Skunkworks/T9602_Library#3]
i connected the T9602-5-D and dont get any value with this code.
it just prints out "Humi" all the time

**Comment by PapaSchIumpf** [comment]
i tried it now with an esp32 and i get values, but its always the same
it prints out "99.99,12.28," all the time.
Does anyone have an idea?

**Comment by awickert** [comment]
Best guess for the first one: the connection may be being cut before the transmission ends.

Second: not sure which sensor this is, but it shouldn't work if this isn't the T9602.

Code would help.

**Comment by PapaSchIumpf** [comment]
i used the very simple code example here with the T9602-5-D
just added #include "Arduino.h"


// Include the T9602 library
#include "T9602.h"
#include "Arduino.h"

// Declare variables -- just as strings
String header;
String data;

// Instantiate class
T9602 mySensor;

void setup(){
    // Begin Serial connection to computer at 38400 baud
    Serial.begin(38400);
    // Obtain the header just once
    header = mySensor.getHeader();
    // Print the header to the serial monitor
    Serial.println(header);
}

void loop(){
    // Take one reading every (10 + time to take reading) seconds
    // and print it to the screen
    mySensor.updateMeasurements();
    data = mySensor.getString();
    Serial.println(data);
    delay(10000); // Wait 10 seconds before the next reading, inefficiently
}

thank you for your help.

**Comment by awickert** [comment]
Thanks for this. I don't have the sensor or a standard arduino with me to test this at the moment. What I can say, however, is that it works on the [Margay](https://github.com/NorthernWidget/Project-Margay) and that I wrote this code based around what we did there, but haven't actually tested it.

Your first test froze partway through `Serial.println(header);`. Perhaps a `delay()` after this could help give it time to finish printing.

Your second one seems to be working, though I wonder with this if the sensor might not be properly connected -- it seems that you're getting values via the I2C bus that could be at some limit of the range.

**Comment by PapaSchIumpf** [comment]
i wrote an mail to the amphenol advanced sensor and got an answer with links and i found this code:

the links:
https://github.com/AmphenolAdvancedSensors/Telaire
https://github.com/AmphenolAdvancedSensors/Telaire/blob/T9602-ChipCap2/T9602.ino


#include "Wire.h"
#include "Arduino.h"

void setup(){
  Serial.begin(115200);  // start serial for output
  Wire.begin();
  Serial.println("Amphenol Advanced Sensors");
  Serial.println("Arduino T9602 Monitor");
}

void getdata(byte *a, byte *b, byte *c, byte *d)
{
  Wire.beginTransmission(0x28);
  Wire.write(0);
  Wire.endTransmission();
  
  Wire.requestFrom(0x28, 4);
  *a = Wire.read();
  *b = Wire.read();
  *c = Wire.read();
  *d = Wire.read();
}
 void showthedata()
{
  byte aa,bb,cc,dd;
  float temperature=0.0;  float humidity=0.0;
  getdata(&aa,&bb,&cc,&dd);
 
// humidity = (rH_High [5:0] x 256 + rH_Low [7:0]) / 16384 x 100
  humidity = (float)(((aa & 0x3F ) << 8) + bb) / 16384.0 * 100.0;

// temperature = (Temp_High [7:0] x 64 + Temp_Low [7:2]/4 ) / 16384 x 165 - 40
  temperature = (float)((unsigned)(cc  * 64) + (unsigned)(dd >> 2 )) / 16384.0 * 165.0 - 40.0;

//static void cc2_calculations(void)
//{
//  raw_rh =
//    (uint32_t)(((uint16_t)(i2c_buf[0] & 0x3F) * 256) + (uint16_t)i2c_buf[1]);
//  cooked_rh = ((double)raw_rh / 16384.0) * 100.0;

//  raw_tc =
//    (int32_t)(((uint16_t)i2c_buf[2] * 64) + ((uint16_t)(i2c_buf[3] & 0xFC) >> 2));
//  cooked_tc = ((double)raw_tc / 16384.0) * 165.0 - 40.0;
//} // cc2_calculations



Serial.print(temperature);Serial.print(" degC  ");Serial.print(humidity);Serial.println(" %rH");;
}

void loop(){

  showthedata();
  
  delay(3000);
}


you just have to replace the i2c adress, it´s 0x00 on default, i used an i2c scanner to find out which one the sensor has
So it works perfectly now:)

**Comment by awickert** [comment]
Great to know that you got it working with the proper I2C address. Closing and archiving this -- it could be useful!
